sudo: true
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 5.5
    - php: 7.1
    - php: 7.2

services:
  - redis-server

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester -p php-cgi -s ./tests/

after_failure:
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
